(self.AMP=self.AMP||[]).push({n:"amp-auto-ads",v:"1907161745080",f:(function(AMP,_){
var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},h;if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var m;a:{var ba={a:!0},n={};try{n.__proto__=ba;m=n.a;break a}catch(a){}m=!1}h=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=h,ca=Object.prototype.toString;function t(a){return a||{}};function v(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function w(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};self.log=self.log||{user:null,dev:null,userForEmbed:null};var x=self.log;function y(){if(!x.user)throw Error("failed to call initLogConstructor");return x.user}function z(a,b){y().assert(a,b,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};var da={type:!0};function A(a,b){if(!a[b])return{};if("[object Object]"!==ca.call(a[b])||Array.isArray(a[b]))return y().warn("amp-auto-ads",b+" property not an object"),{};b=a[b];var c={},e;for(e in b)if(da[e]||w(e,"data-")){var d=typeof b[e];"number"!=d&&"string"!=d&&"boolean"!=d?y().warn("amp-auto-ads","Attribute type not supported: "+d):c[e]=String(b[e])}else y().warn("amp-auto-ads","Attribute not whitlisted: "+e);return c};function ea(a){return a?{top:a.top,bottom:a.bottom,left:a.left,right:a.right}:a};function fa(){var a,b;this.promise=new Promise(function(c,e){a=c;b=e});this.resolve=a;this.reject=b}function ha(a){return new Promise(function(b){b(a())})};function B(){var a=100;this.M=a;this.A=this.D=0;this.w=Object.create(null)}B.prototype.has=function(a){return!!this.w[a]};B.prototype.get=function(a){var b=this.w[a];if(b)return b.access=++this.A,b.payload};
B.prototype.put=function(a,b){this.has(a)||this.D++;this.w[a]={payload:b,access:this.A};if(!(this.D<=this.M)){if(x.dev)a=x.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.w;var c=this.A+1,e;for(e in a){var d=a[e].access;if(d<c){c=d;var f=e}}void 0!==f&&(delete a[f],this.D--)}};t({c:!0,v:!0,a:!0,ad:!0,action:!0});var D,E;
function F(a){var b;D||(D=self.document.createElement("a"),E=self.UrlCache||(self.UrlCache=new B));var c=b?null:E,e=D;if(c&&c.has(a))a=c.get(a);else{e.href=a;e.protocol||(e.href=e.href);var d={href:e.href,protocol:e.protocol,host:e.host,hostname:e.hostname,port:"0"==e.port?"":e.port,pathname:e.pathname,search:e.search,hash:e.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
e.origin&&"null"!=e.origin?e.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;c&&c.put(a,d);a=d}return a};function G(a,b){a=a.__AMP_TOP||a;return H(a,b)}function I(a,b){var c=K(a);c=K(c);c=c.isSingleDoc()?c.win:c;return H(c,b)}function K(a){return a.nodeType?G((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function H(a,b){var c=a.services;c||(c=a.services={});var e=c;a=e[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var L;function M(a,b,c){a=a.createElement(b);for(var e in c)a.setAttribute(e,c[e]);return a}function ia(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}function ja(a,b){return a.closest?a.closest(b):ia(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}
function ka(a,b){if(void 0!==L)var c=L;else{try{var e=a.ownerDocument,d=e.createElement("div"),f=e.createElement("div");d.appendChild(f);c=d.querySelector(":scope div")===f}catch(k){c=!1}c=L=c}c?a=a.querySelectorAll(b.replace(/^|,/g,"$&:scope ")):(a.classList.add("i-amphtml-scoped"),b=b.replace(/^|,/g,"$&.i-amphtml-scoped "),b=a.querySelectorAll(b),a.classList.remove("i-amphtml-scoped"),a=b);return a}
function la(a){w(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new fa;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function N(a){return I(a,"viewport")};var ma=["AMP-SIDEBAR","AMP-APP-BANNER"],na={1:function(a,b){a.parentNode.insertBefore(b,a)},4:function(a,b){a.parentNode.insertBefore(b,a.nextSibling)},2:function(a,b){a.insertBefore(b,a.firstChild)},3:function(a,b){a.appendChild(b)}};function O(a,b,c,e,d,f,k){this.ampdoc=a;this.C=b;this.l=c;this.T=e;this.P=d;this.K=f;this.H=k;this.F=null;this.j=0}O.prototype.getAdElement=function(){return this.F};
O.prototype.getEstimatedPosition=function(){var a=this;return this.C.getElementLayoutBox(this.l).then(function(b){a:switch(a.T){case 1:case 2:b=b.top;break a;case 3:case 4:b=b.bottom;break a;default:throw Error("Unknown position");}return b})};
O.prototype.placeAd=function(a,b,c,e){var d=this;return this.getEstimatedPosition().then(function(f){return c.isTooNearAnAd(f).then(function(c){if(c)return d.j=3,d.j;d.F=oa(d,a,b.width);d.P(d.l,d.getAdElement());return pa(d,b,e).then(function(a){return la(d.getAdElement()).then(function(){return d.getAdElement().whenBuilt()}).then(function(){return d.C.attemptChangeSize(d.getAdElement(),a.height,a.width,a.margins)}).then(function(){d.j=2;return d.j},function(){d.j=1;return d.j})})})})};
function pa(a,b,c){var e=a.C.getViewport(),d=e.getWidth();if(c&&1200>=d){var f=e.getHeight(),k=qa(d,f),l=ea(a.H);return I(a.l,"resources").getElementLayoutBox(a.l).then(function(b){var c;(c=a.ampdoc.win.getComputedStyle(a.l))||(c=Object.create(null));c=c.direction;0!==b.left&&(l=l||{},"rtl"==c?l.right=b.left:l.left=-b.left)}).then(function(){return Promise.resolve({width:d,height:k,margins:l})})}return Promise.resolve({height:b.height||250,margins:a.H})}
function oa(a,b,c){b=Object.assign(t({layout:c?"fixed":"fixed-height",height:"0",width:c?c:"auto","class":"i-amphtml-layout-awaiting-size"}),b,a.K);return M(a.ampdoc.win.document,"amp-ad",b)}function ra(a,b){var c=b.placements;if(!c)return y().info("amp-auto-ads","No placements in config"),[];var e=[];c.forEach(function(b){sa(a,b,e)});return e}
function sa(a,b,c){var e=na[b.pos];if(e){var d=b.anchor;if(d){var f=P(a.getRootNode(),d);if(f.length){var k=void 0;if(b.style){var l=parseInt(b.style.top_m,10),u=parseInt(b.style.bot_m,10);if(l||u)k={top:l||void 0,bottom:u||void 0}}f.forEach(function(d){if(ta(d,b.pos)){var f=A(b,"attributes");c.push(new O(a,I(d,"resources"),d,b.pos,e,f,k))}})}else y().warn("amp-auto-ads","No anchor element found")}else y().warn("amp-auto-ads","No anchor in placement")}else y().warn("amp-auto-ads","No injector for position")}
function P(a,b){var c=b.selector;if(!c)return y().warn("amp-auto-ads","No selector in anchor"),[];c=[].slice.call(ka(a.documentElement||a,c));var e=b.min_c||0;0<e&&(c=c.filter(function(a){return a.textContent.length>=e}));"number"!=typeof b.index&&b.all||(c=(c=c[b.index||0])?[c]:[]);if(0==c.length)return[];if(b.sub){var d=[];c.forEach(function(a){d=d.concat(P(a,b.sub))});return d}return c}
function ta(a,b){var c=1==b||4==b?a.parentElement:a;if(!c)return y().warn("amp-auto-ads","Parentless anchor with BEFORE/AFTER position."),!1;var e=c;return!ma.some(function(a){return ja(e,a)?(y().warn("amp-auto-ads","Placement inside blacklisted ancestor: "+a),!0):!1})}function qa(a,b){var c=100,e=Math.min(300,b),d=Math.round(a/1.2);return Math.min(Math.max(d,c),e)};function Q(a){var b=4096,c,e=[],d=c&&null!=c.value&&""!==c.value?encodeURIComponent(c.name)+"="+encodeURIComponent(String(c.value)):null,f=b-45;d&&(f-=d.length+1);for(var k=Object.keys(a),l=0;l<k.length;l++){var u=k[l],J=a[u];if(null!=J&&""!==J){var r=encodeURIComponent(u)+"=",p=encodeURIComponent(String(J)),C=r.length+p.length+1;if(C>f){var V=p.substr(0,f-r.length-1).replace(/%\w?$/,"");V&&e.push(r+V);d&&e.push(d);break}e.push(r+p);f-=C}}return e.length?"//pagead2.googlesyndication.com/getconfig/ama?"+
e.join("&"):"//pagead2.googlesyndication.com/getconfig/ama"};function ua(a,b){return"adsense"==a?new R(b):"doubleclick"==a?new S(b):null}function R(a){this.h=a}g=R.prototype;g.isEnabled=function(){return!0};g.isResponsiveEnabled=function(){return!0};g.getConfigUrl=function(){var a=I(this.h,"documentInfo").get(),b=F(a.canonicalUrl).hostname;return Q({client:this.h.getAttribute("data-ad-client"),plah:b,ama_t:"amp",url:a.canonicalUrl})};
g.getAttributes=function(){var a=t({type:"adsense","data-ad-client":this.h.getAttribute("data-ad-client")}),b=this.h.getAttribute("data-ad-host");b&&(a["data-ad-host"]=b);return a};g.getDefaultAdConstraints=function(){var a=N(this.h).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};g.getSizing=function(){return{}};function S(a){this.h=a}g=S.prototype;g.isEnabled=function(){return!0};g.isResponsiveEnabled=function(){return!1};
g.getConfigUrl=function(){var a=I(this.h,"documentInfo").get(),b=F(a.canonicalUrl).hostname;return Q({client:this.h.getAttribute("data-ad-legacy-client"),plah:b,ama_t:"amp",url:a.canonicalUrl})};g.getAttributes=function(){return t({type:"doubleclick","data-slot":this.h.getAttribute("data-slot"),json:this.h.getAttribute("data-json")})};
g.getDefaultAdConstraints=function(){var a=N(this.h).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};g.getSizing=function(){var a=this.h.getAttribute("data-experiment");try{var b=JSON.parse(a)}catch(e){b=null}var c=b;return c?{height:c.height?Number(c.height):250,width:c.width?Number(c.width):void 0}:{}};function T(a,b,c,e,d){d=void 0===d?!1:d;this.L=a.slice(0);this.B=b;this.U=c;this.m=e;this.G=0;this.R=d}T.prototype.run=function(){var a=this;return this.m.isMaxAdCountReached()?ha(function(){return U(a)}):va(this).then(function(b){return b?a.run():U(a)})};function U(a){return{adsPlaced:a.G,totalAdsOnPage:a.m.getAdCount()}}
function va(a){var b=a.L.shift();return b?b.placeAd(a.B,a.U,a.m,a.R).then(function(c){return 2==c?(a.m.addAd(b.getAdElement()),a.G++,!0):va(a)}):(y().info("amp-auto-ads","unable to fulfill ad strategy"),Promise.resolve(!1))};function W(a,b){this.o=a;this.O=b.initialMinSpacing;this.J=b.subsequentMinSpacing.slice(0).sort(function(a,b){return a.adCount-b.adCount});this.S=b.maxAdCount;this.I=wa(this)}W.prototype.addAd=function(a){this.o.push(a);this.I=wa(this)};W.prototype.getAdCount=function(){return this.o.length};W.prototype.isMaxAdCountReached=function(){return this.getAdCount()>=this.S};W.prototype.isTooNearAnAd=function(a){return xa(this,a,0)};
function xa(a,b,c){return c>=a.o.length?Promise.resolve(!1):ya(b,a.o[c]).then(function(e){return e<a.I?!0:xa(a,b,c+1)})}function ya(a,b){return I(b,"resources").getElementLayoutBox(b).then(function(b){return a>=b.top&&a<=b.bottom?0:Math.min(Math.abs(a-b.top),Math.abs(a-b.bottom))})}function wa(a){for(var b=a.getAdCount(),c=a.O,e=0;e<a.J.length;e++){var d=a.J[e];d.adCount<=b&&(c=d.spacing)}return c}
function za(a){return[].slice.call(a.getRootNode().querySelectorAll("AMP-AD")).filter(function(a){return a.parentElement&&"AMP-STICKY-AD"==a.parentElement.tagName?!1:!0})}
function Aa(a,b){b=b.adConstraints;if(!b)return null;var c=N(a).getHeight(),e=Ba(b.initialMinSpacing,c);if(null==e)return y().warn("amp-auto-ads","Invalid initial min spacing"),null;var d=(b.subsequentMinSpacing||[]).map(function(a){var b=a.adCount;if(null==b)return y().warn("amp-auto-ads","No subsequentMinSpacing adCount specified"),null;a=Ba(a.spacing,c);return null==a?(y().warn("amp-auto-ads","Invalid subsequent min spacing"),null):{adCount:b,spacing:a}});return-1!=d.indexOf(null)?null:null==b.maxAdCount?
(y().warn("amp-auto-ads","No maxAdCount specified"),null):{initialMinSpacing:e,subsequentMinSpacing:d,maxAdCount:b.maxAdCount}}function Ba(a,b){if(!a)return null;var c=parseFloat(a);return isNaN(c)||0>c?null:v(a,"px")?c:v(a,"vp")?c*b:null};function Ca(a,b,c){this.ampdoc=a;this.B=b;this.N=c}
Ca.prototype.run=function(){if(this.ampdoc.getRootNode().querySelector("AMP-STICKY-AD"))return y().warn("amp-auto-ads","Auto ads may not work because of already existing <amp-sticky-ad>."),Promise.resolve(!1);if(!y().assertArray(this.N.optInStatus||[]).includes(2))return Promise.resolve(!1);G(this.ampdoc.win,"extensions").installExtensionForDoc(this.ampdoc,"amp-sticky-ad","1.0");var a=N(this.ampdoc).getWidth(),b=Object.assign({},this.B,t({width:String(a),height:"100"}));a=this.ampdoc.win.document;
b=M(a,"amp-ad",b);a=M(a,"amp-sticky-ad",t({layout:"nodisplay"}));a.appendChild(b);b=this.ampdoc.getBody();b.insertBefore(a,b.firstChild);return Promise.resolve(!0)};function X(){return AMP.BaseElement.apply(this,arguments)||this}var Y=AMP.BaseElement;X.prototype=aa(Y.prototype);X.prototype.constructor=X;if(q)q(X,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var Da=Object.getOwnPropertyDescriptor(Y,Z);Da&&Object.defineProperty(X,Z,Da)}else X[Z]=Y[Z];X.V=Y.prototype;
X.prototype.buildCallback=function(){var a=this,b=this.element.getAttribute("type");z(b,"Missing type attribute");var c=ua(b,this.element);z(c,"No AdNetworkConfig for type: "+b);if(c.isEnabled(this.win)){var e=this.getAmpDoc();G(this.win,"extensions").installExtensionForDoc(e,"amp-ad");var d=I(this.getAmpDoc(),"viewer"),f=d.whenFirstVisible();f.then(function(){return Ea(a,c.getConfigUrl())}).then(function(b){if(b){var d=b.noConfigReason;if(d)a.user().warn("amp-auto-ads",d);else{var f=ra(e,b),k=Object.assign(c.getAttributes(),
A(b,"attributes")),r=c.getSizing(),p=Aa(e,b)||c.getDefaultAdConstraints();p=new W(za(e),p);(new T(f,k,r,p,c.isResponsiveEnabled())).run();var C=Object.assign(k,A(b,"stickyAdAttributes"));(new Ca(e,C,b)).run()}}})}};X.prototype.isLayoutSupported=function(){return!0};
function Ea(a,b){var c={mode:"cors",method:"GET",credentials:"omit"};return G(a.win,"xhr").fetchJson(b,c).then(function(a){return a.json()}).catch(function(b){a.user().error("amp-auto-ads","amp-auto-ads config xhr failed: "+b);return null})}(function(a){a.registerElement("amp-auto-ads",X)})(self.AMP);
})});

//# sourceMappingURL=amp-auto-ads-0.1.js.map
